Repository jackal998/aicommit, pull requests merged in 2023-03, with the labels that each got.

#4 ci: add conventional pr title action
  .github/workflows/conventional-pr-title.yml
Labels: good first issue

#5 feat: build gem aicommit
  Gemfile
  Gemfile.lock
  aicommit.gemspec
  bin/aicommit
  lib/aicommit.rb
  spells/01_monitor_git_staging.md
  spells/02_contribution.md
  spells/03_gem_aicommit.md
Labels: feature

#6 feat: openai generates commit message
  Gemfile
  Gemfile.lock
  lib/aicommit.rb
  spells/04_generate_commit_message.md
Labels: feature

#8 docs: add readme
  Readme.md
  spells/07_add_readme.md
Labels: documentation

#10 feat: update gemspec to 0.0.4
  aicommit.gemspec
  spells/06_upload_to_rubygems.md
Labels: feature

#11 feat: to objects
  Gemfile
  Gemfile.lock
  bin/aicommit
  lib/aicommit.rb
  lib/commit_message_generator.rb
  lib/git_client.rb
  lib/token_manager.rb
  spec/aicommit_spec.rb
  spec/commit_message_generator_spec.rb
  spec/git_client_spec.rb
  spec/token_manager_spec.rb
  spells/08_git_client.md
  spells/09_token_manager.md
  spells/10_commit_message_generator.md
  spells/11_refactor_aicommit_spec.md
Labels: feature

#14 fix: disposable commit_message_generator
  lib/aicommit.rb
  spec/aicommit_spec.rb
Labels: bug

#15 perf: release 0.0.7
  aicommit.gemspec
Labels: release

#19 feat: CD
  .github/workflows/cd.yml
Labels: feature

#23 fix: update cd flow to use default location
  .github/workflows/cd.yml
Labels: feature

#24 perf: bump up version number to 0.0.8
  aicommit.gemspec
Labels: release

#26 feat: display gem version
  Readme.md
  aicommit.gemspec
  bin/aicommit
  lib/aicommit/version.rb
  push_release_tag.rb
  spells/13_add_run_options.md
  spells/14_update_readme.md
Labels: feature

#27 build: 1.0.0
  lib/aicommit/version.rb
Labels: release
